name: TopoAnalysis
channels:
  - defaults
  - conda-forge
dependencies:
  - affine=2.4.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - babel=2.13.0
  - backcall=0.2.0
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=4.1.0
  - blosc=1.21.3
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.15.1
  - cfitsio=3.470
  - charset-normalizer=2.0.4
  - click=8.2.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cycler=0.11.0
  - cython=3.0.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.7.0
  - fftw=3.3.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.6.2
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=68.1
  - idna=3.4
  - ipykernel=6.25.0
  - ipympl=0.9.6
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.14
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=3.0.5
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.2
  - libgdal=3.6.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.43.2
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp-base=1.5.0
  - libxml2=2.10.4
  - libzip=1.8.0
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - minizip=4.0.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbconvert=5.5.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.21
  - openjpeg=2.3.0
  - openssl=3.5.0
  - packaging=22.0
  - pandas=2.1.1
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - pooch=1.4.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyzmq=23.2.0
  - qhull=2020.2
  - qtconsole-base=5.4.4
  - qtpy=2.4.0
  - rasterio=1.4.3
  - readline=8.2
  - requests=2.28.1
  - richdem=2.3.0
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - testpath=0.6.0
  - tiledb=2.3.3
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2022g
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=4.0.5
  - xerces-c=3.2.4
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - cartopy==0.24.1
      - descartes==1.1.0
      - geopandas==1.1.0
      - imageio==2.37.0
      - joblib==1.3.2
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - narwhals==1.26.0
      - networkx==3.4.2
      - numba==0.61.2
      - patsy==0.5.4
      - pillow==11.2.1
      - plotly==6.0.0
      - pyflwdir==0.5.10
      - pyogrio==0.11.0
      - pyproj==3.7.1
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.12
      - pyqt5-sip==12.13.0
      - pyshp==2.3.1
      - scikit-image==0.25.2
      - scikit-learn==1.3.2
      - scipy==1.15.3
      - shapely==2.0.2
      - statsmodels==0.14.0
      - threadpoolctl==3.2.0
      - tifffile==2025.5.10
      - tqdm==4.66.2
prefix: /Users/scdobbs/miniforge3/envs/TopoAnalysis
